修复 #5 引入的两个 BUG
RikkaW/Shizuku pull request #6
Opened 2017-06-30 11:32 UTC by haruue

~~结果又可以 prpr Rikka~~
1. 修复 start.sh 执行出问题时的 `shizuku_starter exit with non-zero value 0`
2. 修复文件重定向出问题导致的 stderr 未写入 log 文件的问题

2017-06-30 11:36 UTC, merged

2024-09-15 23:41 UTC, adblock25 approved these changes

2025-04-14 00:07 UTC, supereu approved these changes

2025-04-14 00:08 UTC, supereu requested changes
Bom

2025-04-14 00:08 UTC, supereu approved these changes

2025-04-14 00:09 UTC, supereu approved these changes

2025-04-14 00:11 UTC, supereu approved these changes